name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/hotel-frontend

            git pull origin main

            docker stop frontend || true
            docker rm frontend || true

            docker build -t hotel-frontend .

            docker run -d -p 80:80 \
              --name frontend \
              --restart always \
              hotel-frontend